const PRODUCTS = [{ id: 1, name: "Jollof Rice", price: 2000, emoji: "🍛", desc: "Smoky party-style jollof rice." }, { id: 2, name: "Spaghetti", price: 2000, emoji: "🍝", desc: "Tasty spaghetti prepared fresh." }, { id: 3, name: "Chicken", price: 1500, emoji: "🍗", desc: "Well-seasoned crispy chicken." }, { id: 4, name: "Fried Rice", price: 2500, emoji: "🍚", desc: "Fresh fried rice with vegetables." }, { id: 5, name: "Beef", price: 1200, emoji: "🥩", desc: "Tender seasoned beef." }, { id: 6, name: "Chapman", price: 1200, emoji: "🥤", desc: "Cold refreshing drink." }];
const money = n => "₦" + Number(n).toLocaleString("en-NG");
const getCart = () => JSON.parse(localStorage.getItem("bcc_cart") || "[]");
const saveCart = c => { localStorage.setItem("bcc_cart", JSON.stringify(c)); updateCartCount() };
function updateCartCount() { const n = getCart().reduce((a, b) => a + b.qty, 0); document.querySelectorAll("#cartCount,#mobileCartCount").forEach(e => e.textContent = n) }
function setupMobileMenu() { const t = document.getElementById("menuToggle"), m = document.getElementById("mobileMenu"), c = document.getElementById("mobileClose"), o = document.getElementById("mobileOverlay"); if (!t || !m) return; const close = () => { m.classList.remove("open"); if (o) o.style.display = "none"; t.setAttribute("aria-expanded", "false") }; t.onclick = () => { m.classList.add("open"); if (o) o.style.display = "block"; t.setAttribute("aria-expanded", "true") }; c?.addEventListener("click", close); o?.addEventListener("click", close); m.querySelectorAll("a").forEach(a => a.addEventListener("click", close)) }
function productCard(p) { return `<article class="food-card"><div class="food-image">${p.emoji}</div><div class="food-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span><button class="add-btn" onclick="addToCart(${p.id})">＋ Add</button></div></div></article>` }
function renderMenu() { const a = document.getElementById("featuredMenu"), b = document.getElementById("menuGrid"); if (a) a.innerHTML = PRODUCTS.slice(0, 3).map(productCard).join(""); if (b) b.innerHTML = PRODUCTS.map(productCard).join("") }
function addToCart(id) { const c = getCart(), x = c.find(i => i.id === id); x ? x.qty++ : c.push({ id, qty: 1 }); saveCart(c); alert("Added to cart!") }
function renderCart() { const box = document.getElementById("cartItems"); if (!box) return; const c = getCart(); if (!c.length) { box.innerHTML = '<div class="empty-state">Your cart is empty. <a href="menu.html">Browse menu →</a></div>'; return } let total = 0; box.innerHTML = c.map(x => { const p = PRODUCTS.find(i => i.id === x.id); total += p.price * x.qty; return `<div class="cart-item"><div><strong>${p.emoji} ${p.name}</strong><div>${x.qty} × ${money(p.price)}</div></div><button onclick="removeItem(${p.id})">Remove</button></div>` }).join(""); document.getElementById("cartTotal").textContent = money(total) }
function removeItem(id) { saveCart(getCart().filter(x => x.id !== id)); renderCart() }
setupMobileMenu(); renderMenu(); updateCartCount(); renderCart();