const PRODUCTS=[
{id:1,name:"Jollof Rice",price:2000,emoji:"🍛",desc:"Smoky party-style jollof rice."},
{id:2,name:"Spaghetti",price:2000,emoji:"🍝",desc:"Tasty spaghetti prepared fresh."},
{id:3,name:"Chicken",price:1500,emoji:"🍗",desc:"Well-seasoned crispy chicken."},
{id:4,name:"Fried Rice",price:2500,emoji:"🍚",desc:"Fresh fried rice with vegetables."},
{id:5,name:"Beef",price:1200,emoji:"🥩",desc:"Tender seasoned beef."},
{id:6,name:"Chapman",price:1200,emoji:"🥤",desc:"Cold refreshing drink."}
];
const money=n=>"₦"+Number(n).toLocaleString("en-NG");
const getCart=()=>JSON.parse(localStorage.getItem("bcc_cart")||"[]");
const saveCart=c=>{localStorage.setItem("bcc_cart",JSON.stringify(c));updateCartCount()};
function updateCartCount(){const el=document.getElementById("cartCount");if(el)el.textContent=getCart().reduce((a,b)=>a+b.qty,0)}
function productCard(p){return `<article class="food-card"><div class="food-image">${p.emoji}</div><div class="food-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="price-row"><span class="price">${money(p.price)}</span><button class="add-btn" onclick="addToCart(${p.id})">＋ Add</button></div></div></article>`}
function renderMenu(){const a=document.getElementById("featuredMenu"),b=document.getElementById("menuGrid");if(a)a.innerHTML=PRODUCTS.slice(0,3).map(productCard).join("");if(b)b.innerHTML=PRODUCTS.map(productCard).join("")}
function addToCart(id){let c=getCart(),item=c.find(x=>x.id===id);if(item)item.qty++;else c.push({id,qty:1});saveCart(c);alert("Added to cart!")}
function renderCart(){const box=document.getElementById("cartItems");if(!box)return;let c=getCart();if(!c.length){box.innerHTML='<div class="empty-state">Your cart is empty. <a href="menu.html" style="color:#df7d13;font-weight:800">Browse menu →</a></div>';document.getElementById("cartTotal").textContent="₦0";return}let total=0;box.innerHTML=c.map(x=>{let p=PRODUCTS.find(p=>p.id===x.id),t=p.price*x.qty;total+=t;return `<div class="cart-item"><div><strong>${p.emoji} ${p.name}</strong><div>${x.qty} × ${money(p.price)}</div></div><button onclick="removeItem(${p.id})">Remove</button></div>`}).join("");document.getElementById("cartTotal").textContent=money(total)}
function removeItem(id){saveCart(getCart().filter(x=>x.id!==id));renderCart()}
function getUser(){return JSON.parse(localStorage.getItem("bcc_user")||"null")}
function initAuth(){const reg=document.getElementById("registerForm");if(reg)reg.onsubmit=e=>{e.preventDefault();let f=new FormData(reg);let user={name:f.get("name"),phone:f.get("phone"),email:f.get("email"),password:f.get("password")};localStorage.setItem("bcc_user",JSON.stringify(user));document.getElementById("authMessage").textContent="Account created. Redirecting...";setTimeout(()=>location.href="account.html",500)};const login=document.getElementById("loginForm");if(login)login.onsubmit=e=>{e.preventDefault();let u=getUser(),f=new FormData(login);if(!u||((f.get("identifier")!==u.email)&&(f.get("identifier")!==u.phone))||f.get("password")!==u.password){document.getElementById("authMessage").textContent="Login details are not correct.";return}localStorage.setItem("bcc_logged_in","1");location.href="account.html"}}
function initAccount(){const u=getUser();if(!u){location.href="login.html";return}document.getElementById("accountName").textContent=u.name.split(" ")[0];document.getElementById("profileName").textContent=u.name;document.getElementById("profilePhone").textContent=u.phone;document.getElementById("profileEmail").textContent=u.email||"Not added";let bal=Number(localStorage.getItem("bcc_demo_balance")||0);let wb=document.getElementById("walletBalance");if(wb)wb.textContent=money(bal);document.getElementById("logoutBtn").onclick=()=>{localStorage.removeItem("bcc_logged_in");location.href="index.html"}}
function initWallet(){let bal=Number(localStorage.getItem("bcc_demo_balance")||0);const amount=document.getElementById("walletAmount");if(amount)amount.textContent=money(bal);const btn=document.getElementById("depositBtn");if(btn)btn.onclick=()=>alert("Demo wallet only. The next backend version will connect this button to secure Paystack/Flutterwave payment verification.");}
function initOrders(){const box=document.getElementById("ordersList");if(!box)return;let orders=JSON.parse(localStorage.getItem("bcc_orders")||"[]");if(orders.length)box.innerHTML=orders.map(o=>`<div class="order-card"><div class="order-top"><strong>Order #${o.id}</strong><span class="status">${o.status}</span></div><p>${o.items} · ${money(o.total)}</p><small>${o.date}</small></div>`).join("")}
function initCheckout(){const b=document.getElementById("checkoutBtn");if(b)b.onclick=()=>{if(!getUser()){alert("Please create an account or login before checkout.");location.href="login.html";return}let c=getCart();if(!c.length)return;let total=c.reduce((s,x)=>s+PRODUCTS.find(p=>p.id===x.id).price*x.qty,0),orders=JSON.parse(localStorage.getItem("bcc_orders")||"[]");orders.unshift({id:Date.now().toString().slice(-6),status:"Confirmed",items:c.map(x=>`${x.qty}× ${PRODUCTS.find(p=>p.id===x.id).name}`).join(", "),total,date:new Date().toLocaleString()});localStorage.setItem("bcc_orders",JSON.stringify(orders));localStorage.setItem("bcc_cart","[]");location.href="orders.html"}}
renderMenu();updateCartCount();renderCart();initAuth();initAccount();initWallet();initOrders();initCheckout();
